baseURL       = "https://instagram-lovelyfox-code.vercel.app/"
languageCode  = "en-us"
title         = "Alina | creator"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Главная"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Обо мне"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Портфолио"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Блог"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Фильтры"
    url     = "filters"
    weight  = 5
  [[menu.nav]]
    name    = "Напиши мне"
    url     = "contact"
    weight  = 6

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Алина | Frontend разработчик | Spark AR creator"
  
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Имя"
    placeholder_email             = "Email"
    placeholder_project_type      = "Проект"
    placeholder_about_the_project = "Детали"
    send_message                  = "Отправить"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Вебсайт"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Фильтр инстаграмм"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Связаться"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/pngtree-pure-color-watercolor-graffiti-gradient-background-board-design-board-design-image_66713.jpeg"
    heading               = "упакую твой бренд в красивую обертку"
    tagline               = "Я Frontend разработчик и Spark AR creator"
    primary_button        = "Смотри мои работы"
    primary_button_url    = "portfolio"
    secondary_button      = "Напиши мне"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "мои работы"
    subtitle  = "Каждый проект наполняю любовью"

  [params.filters]
    enable    = true
    title     = "ФИЛЬТРЫ ДЛЯ ИНСТАГРАММА"
    subtitle  = "Cмотри примеры, вдохновляйся. Создавай свои собственные вместе со мной!"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Давай сотрудничать"
    primary_button      = "Напиши мне"
    primary_button_url  = "contact"
    secondary_button    = "Дай подумать"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Информация"
      phone   = "+31630792944"
      email   = "alinadakhno60@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Навигация по сайту"
        [[params.footer.sitemap.link]]
          name = "Обо мне"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Портфолио"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Блог"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Связаться со мной"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Я в соцсетях"
        [[params.footer.social.link]]
          name = "linkedin"
          url  = "#"
        [[params.footer.social.link]]
          name = "instagram"
          url  = "#"
        [[params.footer.social.link]]
          name = "telegram"
          url  = "#"
        
      # Footer Service
      # [params.footer.service]
      #   title       = "We help brands:"
      #   description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"